version: '3'
services:
  web:
    build: .
    image: "ncpractice172nti/ncpractice_web-app"
    links:
     - database
    ports:
     - "80:8090"
  database:
    image: "mongo:latest"
    ports:
     - "27017:27017"